### ISSUE TITLE
Tag configs which don't specify a dataset in their included_uris are failing

### ISSUE THREAD

**Issue by shirleycohen** [GoogleCloudPlatform/datacatalog-tag-engine#19]
Add support for included_uris of the form: bigquery/project/my-project/*

Log entries:

2021-11-09 15:54:02 default[prod]  [2021-11-09 15:54:02,244] ERROR in app: Exception on /dynamic_auto_update [POST]
2021-11-09 15:54:02 default[prod]  Traceback (most recent call last):    File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app      response = self.full_dispatch_request()    File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request      rv = self.handle_user_exception(e)    File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception      reraise(exc_type, exc_value, tb)    File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise      raise value    File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request      rv = self.dispatch_request()    File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request      return self.view_functions[rule.endpoint](**req.view_args)    File "/srv/main.py", line 1187, in dynamic_auto_update      dcu.create_update_dynamic_tags(    File "/srv/DataCatalogUtils.py", line 523, in create_update_dynamic_tags      resources = rs.get_resources(included_uris, excluded_uris)    File "/srv/Resources.py", line 36, in get_resources      included_resources = self.find_resources(included_uris)    File "/srv/Resources.py", line 88, in find_resources      dataset = split_path[4]  IndexError: list index out of range

**Comment by shirleycohen** [comment]
Fixed
